#  docker-compose up -d

version: "3.8"

services:
  postgres:
    image: postgres
    container_name: jpa_app
    environment:
      POSTGRES_USER: "${DB_USER_ID}"
      POSTGRES_PASSWORD: "${DB_USER_PASSWORD}"
    ports:
      - '5500:5432'
    volumes:
      - ${POSTGRES_HOME_DIR}:/var/lib/postgresql/jpa_app