## http://mageddo.com/tools/yaml-converter

server:
  port: 3030

## database 접속 설정
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/study_db
    username: study_admin
    password: study_admin
  jpa:
    properties:
      hibernate:
#        show_sql: true System.out.print로 출력하기 때문에 사용하지않음
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: 'true'
    hibernate:
      ddl-auto: update

    database-platform: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    deserialization:
      fail_on_unknown_properties: true
  profiles:
    active: 'local'
  mail:
    host: smtp.gmail.com
    port: 587
    username: ENC(6LRP8klnufj2dlTXRjeMeZH2haABDx7Mbe4rlW7CsWE=)
    password: ENC(mynbh2y9fnpRHEHDAnH8xdIxn44t98qFSwigkQ6m484=)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
        SQL: debug # logger로 출력

jasypt:
  encryptor:
    bean: jasyptStringEncryptor